server {
    listen 80;
    server_name tg4you.ru www.tg4you.ru;

    client_max_body_size 10m;

    location = /health {
        proxy_pass http://127.0.0.1:3100;
        include proxy_params;
    }

    location ^~ /api/ {
        proxy_pass http://127.0.0.1:3100;
        include proxy_params;
    }

    location ^~ /auth/ {
        proxy_pass http://127.0.0.1:3100;
        include proxy_params;
    }

    location ^~ /telegram/ {
        proxy_pass http://127.0.0.1:3100;
        include proxy_params;
    }

    location ^~ /uploads/telegram/ {
        proxy_pass http://127.0.0.1:3100;
        include proxy_params;
    }

    location ^~ /public/ {
        proxy_pass http://127.0.0.1:3100;
        include proxy_params;
    }

    location / {
        proxy_pass http://127.0.0.1:3101;
        include proxy_params;
    }
}
